# Generated by Django 2.1.15 on 2021-04-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('Adminid', models.CharField(db_column='Adminid', max_length=9)),
                ('Pseudo', models.CharField(db_column='Pseudo', max_length=10)),
                ('Password', models.CharField(db_column='Password', max_length=10)),
                ('Email', models.TextField(db_column='Email')),
            ],
            options={
                'db_table': 'admin',
                'managed': True,
            },
        ),
    ]
