# Generated by Django 2.1.15 on 2021-04-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyPlay', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminmodel',
            options={'managed': False},
        ),
    ]
