# Generated by Django 2.1.15 on 2021-05-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyPlay', '0002_auto_20210401_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminmodel',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='parentsmodel',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to=''),
        ),
    ]
