pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'amarhabneen/django_team24'
                }
            }
            steps {
                sh 'python -m py_compile StudyPlay/models.py StudyPlay/views.py'
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'amarhabneen/django_team24'
                }
            }
            steps {
                sh 'python -m py_compile StudyPlay/models.py StudyPlay/views.py'
            }
            /*post {
                always {
                    junit 'test-reports/results.xml'
                }*/
            }
        }
    }
